/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 이메일 가입 (US1-AC1~AC3) */
    post: operations["signup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 이메일 로그인 (US2-AC1~AC4) */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/oauth/{provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 외부 계정 인가 코드 교환과 로그인 (US3-AC1~AC3) */
    post: operations["oauthLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 세션 갱신 (US4-AC1~AC3) */
    post: operations["refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 현재 세션 무효화 (US2-AC5) */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/members/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 내 프로필 (FR-015). 온보딩 전에도 호출할 수 있다 */
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/members/nickname-availability": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 닉네임 사용 가능 여부 (US1-AC5, US1-AC6) */
    get: operations["checkNickname"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/members/me/onboarding": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** 온보딩 완료 (US1-AC4~AC6) */
    put: operations["completeOnboarding"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorResponse: {
      /**
       * @description ErrorCode 이름
       * @example INVALID_CREDENTIALS
       */
      code: string;
      message: string;
      /** @description LOGIN_THROTTLED일 때만 있다 */
      retryAfterSeconds?: number;
    };
    ErrorEnvelope: {
      /** @constant */
      success: false;
      data: null;
      error: components["schemas"]["ErrorResponse"];
    };
    /** @enum {string} */
    JobRole:
      | "PLANNING"
      | "DESIGN"
      | "DEVELOPMENT"
      | "MARKETING"
      | "SALES"
      | "HR"
      | "GENERAL_AFFAIRS"
      | "PRODUCTION"
      | "ACCOUNTING"
      | "OTHER";
    /** @enum {string} */
    CareerYear:
      | "NEWCOMER"
      | "YEAR_1"
      | "YEAR_2"
      | "YEAR_3"
      | "YEAR_4"
      | "YEAR_5"
      | "YEAR_6"
      | "YEAR_7_PLUS";
    /** @enum {string} */
    AuthMethod: "EMAIL" | "KAKAO" | "GOOGLE";
    MemberProfile: {
      /** Format: int64 */
      id: number;
      authMethod: components["schemas"]["AuthMethod"];
      email?: string | null;
      nickname?: string | null;
      jobRole?: components["schemas"]["JobRole"] | null;
      careerYear?: components["schemas"]["CareerYear"] | null;
      onboarded: boolean;
    };
    AuthTokens: {
      accessToken: string;
      /** Format: date-time */
      accessTokenExpiresAt: string;
      /** @description refresh 유예 구간(교체 후 30초)에서는 null이다. 이때 BFF는 refresh 쿠키를 바꾸지 않는다. */
      refreshToken: string | null;
      /** Format: date-time */
      refreshTokenExpiresAt: string;
    };
    AuthResult: {
      member: components["schemas"]["MemberProfile"];
      tokens: components["schemas"]["AuthTokens"];
      /** @description 이번 요청으로 회원이 만들어졌으면 true */
      newMember: boolean;
    };
    AuthResultEnvelope: {
      /** @constant */
      success: true;
      data: components["schemas"]["AuthResult"];
      error: null;
    };
    MemberProfileEnvelope: {
      /** @constant */
      success: true;
      data: components["schemas"]["MemberProfile"];
      error: null;
    };
    OnboardingResult: {
      member: components["schemas"]["MemberProfile"];
      /** @description onboarded=true 클레임을 담은 새 access 토큰 */
      accessToken: string;
      /** Format: date-time */
      accessTokenExpiresAt: string;
    };
    NicknameAvailability: {
      available: boolean;
      /** @enum {string|null} */
      reason?: "INVALID_FORMAT" | "TAKEN" | null;
    };
    EmailPasswordRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
  };
  responses: {
    /** @description 입력 검증 실패 (INVALID_REQUEST) */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description 인증 없음 또는 세션 만료, 무효 (UNAUTHORIZED, SESSION_EXPIRED) */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
  };
  parameters: {
    /** @description BFF와 API가 공유하는 비밀 키. 맞을 때만 X-Ogu-Client-Ip를 믿는다. */
    BffKey: string;
    /** @description 브라우저의 원래 IP. 로그인 실패 제한에 쓴다. */
    ClientIp: string;
    Provider: "kakao" | "google";
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  signup: {
    parameters: {
      query?: never;
      header?: {
        /** @description BFF와 API가 공유하는 비밀 키. 맞을 때만 X-Ogu-Client-Ip를 믿는다. */
        "X-Ogu-Bff-Key"?: components["parameters"]["BffKey"];
        /** @description 브라우저의 원래 IP. 로그인 실패 제한에 쓴다. */
        "X-Ogu-Client-Ip"?: components["parameters"]["ClientIp"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailPasswordRequest"];
      };
    };
    responses: {
      /** @description 가입과 동시에 로그인된다. member.onboarded는 false다. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResultEnvelope"];
        };
      };
      400: components["responses"]["BadRequest"];
      /** @description 이미 가입된 이메일(EMAIL_ALREADY_REGISTERED), 또는 외부 계정 회원이 쓰는 이메일(EMAIL_REGISTERED_WITH_OTHER_METHOD) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: {
        /** @description BFF와 API가 공유하는 비밀 키. 맞을 때만 X-Ogu-Client-Ip를 믿는다. */
        "X-Ogu-Bff-Key"?: components["parameters"]["BffKey"];
        /** @description 브라우저의 원래 IP. 로그인 실패 제한에 쓴다. */
        "X-Ogu-Client-Ip"?: components["parameters"]["ClientIp"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailPasswordRequest"];
      };
    };
    responses: {
      /** @description 로그인 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResultEnvelope"];
        };
      };
      400: components["responses"]["BadRequest"];
      /** @description 이메일 또는 비밀번호가 틀림. 어느 쪽인지 구분하지 않는다 (INVALID_CREDENTIALS) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description 로그인 실패 제한에 걸림 (LOGIN_THROTTLED). error.retryAfterSeconds와 Retry-After 헤더가 있다 */
      429: {
        headers: {
          "Retry-After"?: number;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  oauthLogin: {
    parameters: {
      query?: never;
      header?: {
        /** @description BFF와 API가 공유하는 비밀 키. 맞을 때만 X-Ogu-Client-Ip를 믿는다. */
        "X-Ogu-Bff-Key"?: components["parameters"]["BffKey"];
        /** @description 브라우저의 원래 IP. 로그인 실패 제한에 쓴다. */
        "X-Ogu-Client-Ip"?: components["parameters"]["ClientIp"];
      };
      path: {
        provider: components["parameters"]["Provider"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          code: string;
          /**
           * Format: uri
           * @description 인가 요청에 쓴 redirect_uri와 같아야 한다. API는 허용 목록과 대조한다
           */
          redirectUri: string;
          /** @description PKCE를 쓴 경우에만 보낸다 */
          codeVerifier?: string | null;
        };
      };
    };
    responses: {
      /** @description 로그인 성공. 처음이면 newMember=true, member.onboarded=false */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResultEnvelope"];
        };
      };
      400: components["responses"]["BadRequest"];
      /** @description 제공자가 코드를 거절함 (OAUTH_CODE_INVALID) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description 같은 이메일이 이메일 가입으로 이미 쓰임 (EMAIL_REGISTERED_WITH_OTHER_METHOD) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description 제공자가 응답하지 않음 (OAUTH_PROVIDER_UNAVAILABLE) */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: {
        /** @description BFF와 API가 공유하는 비밀 키. 맞을 때만 X-Ogu-Client-Ip를 믿는다. */
        "X-Ogu-Bff-Key"?: components["parameters"]["BffKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          refreshToken: string;
        };
      };
    };
    responses: {
      /** @description 새 토큰. 유예 구간에서는 tokens.refreshToken이 null */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResultEnvelope"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 세션이 무효가 되었다. 이미 무효이거나 만료된 세션의 토큰은 401이다(BFF는 결과와 관계없이 쿠키를 지운다) */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 내 프로필 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberProfileEnvelope"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  checkNickname: {
    parameters: {
      query: {
        nickname: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 사용 가능 여부 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            success: true;
            data: components["schemas"]["NicknameAvailability"];
            error: null;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  completeOnboarding: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          nickname: string;
          jobRole: components["schemas"]["JobRole"];
          careerYear: components["schemas"]["CareerYear"];
        };
      };
    };
    responses: {
      /** @description 온보딩 완료. 새 access 토큰을 함께 준다 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            success: true;
            data: components["schemas"]["OnboardingResult"];
            error: null;
          };
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      /** @description 닉네임 중복(NICKNAME_TAKEN) 또는 이미 온보딩함(ALREADY_ONBOARDED) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
}
