/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 이메일 가입 (US1-AC1~AC3) */
    post: operations["signup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 이메일 로그인 (US2-AC1~AC4) */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/oauth/{provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 외부 계정 인가 코드 교환과 로그인 (US3-AC1~AC3) */
    post: operations["oauthLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 세션 갱신 (US4-AC1~AC3) */
    post: operations["refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 현재 세션 무효화 (US2-AC5) */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/members/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 내 프로필 (FR-015). 온보딩 전에도 호출할 수 있다 */
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/members/nickname-availability": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 닉네임 사용 가능 여부 (US1-AC5, US1-AC6) */
    get: operations["checkNickname"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/members/me/onboarding": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** 온보딩 완료 (US1-AC4~AC6) */
    put: operations["completeOnboarding"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/posts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 고민 글 작성 (US1-AC1, AC2). 감정 분석은 비동기 */
    post: operations["createPost"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/posts/{postId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: components["parameters"]["PostId"];
      };
      cookie?: never;
    };
    /** 글 상세 (FR-012, FR-015). 분석 중이면 monster는 null */
    get: operations["getPostDetail"];
    put?: never;
    post?: never;
    /** 글 삭제 (US4-AC2) */
    delete: operations["deletePost"];
    options?: never;
    head?: never;
    /** 글 수정 (US4-AC1). 몬스터는 바뀌지 않는다 */
    patch: operations["updatePost"];
    trace?: never;
  };
  "/api/v1/feed": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 피드 (US2) */
    get: operations["getFeed"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/posts/{postId}/likes": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: components["parameters"]["PostId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 글 공감 (US3-AC1, US3-AC8) */
    post: operations["likePost"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/posts/{postId}/likes/me": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: components["parameters"]["PostId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** 글 공감 취소 (US3-AC6). HP는 돌아오지 않는다 */
    delete: operations["unlikePost"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/posts/{postId}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: components["parameters"]["PostId"];
      };
      cookie?: never;
    };
    /** 댓글 목록. 원 댓글 50개씩, 답글은 원 댓글 아래에 모두 */
    get: operations["getComments"];
    put?: never;
    /** 댓글 또는 답글 작성 (US3-AC2, AC3) */
    post: operations["createComment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/comments/{commentId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        commentId: components["parameters"]["CommentId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** 댓글 삭제 (US4-AC3). 원 댓글이면 답글도 함께 삭제 */
    delete: operations["deleteComment"];
    options?: never;
    head?: never;
    /** 댓글 수정 (US4-AC3) */
    patch: operations["updateComment"];
    trace?: never;
  };
  "/api/v1/comments/{commentId}/likes": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        commentId: components["parameters"]["CommentId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 댓글 공감 (US3-AC4) */
    post: operations["likeComment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/comments/{commentId}/likes/me": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        commentId: components["parameters"]["CommentId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** 댓글 공감 취소 (US3-AC6) */
    delete: operations["unlikeComment"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorResponse: {
      /**
       * @description ErrorCode 이름
       * @example INVALID_CREDENTIALS
       */
      code: string;
      message: string;
      /** @description LOGIN_THROTTLED일 때만 있다 */
      retryAfterSeconds?: number;
    };
    ErrorEnvelope: {
      /** @constant */
      success: false;
      data: null;
      error: components["schemas"]["ErrorResponse"];
    };
    /** @enum {string} */
    JobRole:
      | "PLANNING"
      | "DESIGN"
      | "DEVELOPMENT"
      | "MARKETING"
      | "SALES"
      | "HR"
      | "GENERAL_AFFAIRS"
      | "PRODUCTION"
      | "ACCOUNTING"
      | "OTHER";
    /** @enum {string} */
    CareerYear:
      | "NEWCOMER"
      | "YEAR_1"
      | "YEAR_2"
      | "YEAR_3"
      | "YEAR_4"
      | "YEAR_5"
      | "YEAR_6"
      | "YEAR_7_PLUS";
    /** @enum {string} */
    AuthMethod: "EMAIL" | "KAKAO" | "GOOGLE";
    MemberProfile: {
      /** Format: int64 */
      id: number;
      authMethod: components["schemas"]["AuthMethod"];
      email?: string | null;
      nickname?: string | null;
      jobRole?: components["schemas"]["JobRole"] | null;
      careerYear?: components["schemas"]["CareerYear"] | null;
      onboarded: boolean;
    };
    AuthTokens: {
      accessToken: string;
      /** Format: date-time */
      accessTokenExpiresAt: string;
      /** @description refresh 유예 구간(교체 후 30초)에서는 null이다. 이때 BFF는 refresh 쿠키를 바꾸지 않는다. */
      refreshToken: string | null;
      /** Format: date-time */
      refreshTokenExpiresAt: string;
    };
    AuthResult: {
      member: components["schemas"]["MemberProfile"];
      tokens: components["schemas"]["AuthTokens"];
      /** @description 이번 요청으로 회원이 만들어졌으면 true */
      newMember: boolean;
    };
    AuthResultEnvelope: {
      /** @constant */
      success: true;
      data: components["schemas"]["AuthResult"];
      error: null;
    };
    MemberProfileEnvelope: {
      /** @constant */
      success: true;
      data: components["schemas"]["MemberProfile"];
      error: null;
    };
    OnboardingResult: {
      member: components["schemas"]["MemberProfile"];
      /** @description onboarded=true 클레임을 담은 새 access 토큰 */
      accessToken: string;
      /** Format: date-time */
      accessTokenExpiresAt: string;
    };
    NicknameAvailability: {
      available: boolean;
      /** @enum {string|null} */
      reason?: "INVALID_FORMAT" | "TAKEN" | null;
    };
    EmailPasswordRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    /** @enum {string} */
    CommentTone:
      "VENT_WITH_ME" | "COMFORT_ME" | "WARM_ADVICE" | "MAKE_ME_LAUGH";
    /** @enum {string} */
    EmotionType:
      "ANXIETY" | "LETHARGY" | "LONELINESS" | "SELF_DEPRECATION" | "IRRITATION";
    /** @enum {string} */
    AnalysisStatus: "PENDING" | "ANALYZED" | "DEFAULTED";
    MonsterView: {
      emotion: components["schemas"]["EmotionType"];
      hp: number;
      /** @enum {integer} */
      maxHp: 10 | 20 | 30;
      /** @enum {string} */
      status: "ALIVE" | "DEFEATED";
    };
    Author: {
      /** Format: int64 */
      id: number;
      nickname: string;
      jobRole: components["schemas"]["JobRole"];
      careerYear: components["schemas"]["CareerYear"];
    };
    PostWriteRequest: {
      /** @description 앞뒤 공백을 뺀 글자(grapheme) 1~500자 */
      content: string;
      commentTone: components["schemas"]["CommentTone"];
    };
    PostUpdateRequest: {
      content?: string;
      commentTone?: components["schemas"]["CommentTone"];
    };
    PostCreated: {
      /** Format: int64 */
      postId: number;
      analysisStatus: components["schemas"]["AnalysisStatus"];
    };
    FeedItem: {
      /** Format: int64 */
      postId: number;
      author: components["schemas"]["Author"];
      /** @description 앞 50글자. 더 길면 끝에 "..." */
      contentPreview: string;
      analysisStatus: components["schemas"]["AnalysisStatus"];
      /** @description 분석 중이면 null */
      monster?: components["schemas"]["MonsterView"] | null;
      likeCount: number;
      likedByMe: boolean;
      commentCount: number;
      /** Format: date-time */
      createdAt: string;
    };
    FeedPage: {
      items: components["schemas"]["FeedItem"][];
      /** @description 다음 페이지가 없으면 null. 불투명 문자열 */
      nextCursor: string | null;
    };
    PostDetail: {
      /** Format: int64 */
      postId: number;
      author: components["schemas"]["Author"];
      content: string;
      commentTone: components["schemas"]["CommentTone"];
      analysisStatus: components["schemas"]["AnalysisStatus"];
      monster?: components["schemas"]["MonsterView"] | null;
      likeCount: number;
      likedByMe: boolean;
      commentCount: number;
      /** @description 내가 쓴 글이면 true */
      mine: boolean;
      /** @description 내 댓글이 이미 HP에 반영됐으면 true. 웹의 낙관적 HP 계산(research R6)에 쓴다 */
      myCommentCounted?: boolean;
      /** Format: date-time */
      createdAt: string;
    };
    Comment: {
      /** Format: int64 */
      commentId: number;
      author: components["schemas"]["Author"];
      content: string;
      likeCount: number;
      likedByMe: boolean;
      mine: boolean;
      /** Format: date-time */
      createdAt: string;
      /** @description 답글(오래된 순). 답글의 replies는 항상 빈 배열이다 */
      replies: components["schemas"]["Comment"][];
    };
    CommentPage: {
      /** @description 원 댓글(오래된 순)과 각 답글 */
      items: components["schemas"]["Comment"][];
      nextCursor: string | null;
    };
    CommentWriteRequest: {
      /** @description 앞뒤 공백을 뺀 글자 1~300자 */
      content: string;
      /**
       * Format: int64
       * @description 답글이면 원 댓글 ID
       */
      parentId?: number | null;
    };
    LikeResult: {
      likeCount: number;
      likedByMe: boolean;
    };
  };
  responses: {
    /** @description 입력 검증 실패 (INVALID_REQUEST). 댓글 작성에서는 INVALID_PARENT_COMMENT도 쓴다 */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description 인증 없음 또는 세션 만료, 무효 (UNAUTHORIZED, SESSION_EXPIRED) */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description 온보딩 전(ONBOARDING_REQUIRED) 또는 권한 없음(NOT_AUTHOR, CANNOT_LIKE_OWN_POST) */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description 없거나 삭제된 글 또는 댓글 (POST_NOT_FOUND, COMMENT_NOT_FOUND) */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
  };
  parameters: {
    /** @description BFF와 API가 공유하는 비밀 키. 맞을 때만 X-Ogu-Client-Ip를 믿는다. */
    BffKey: string;
    /** @description 브라우저의 원래 IP. 로그인 실패 제한에 쓴다. */
    ClientIp: string;
    Provider: "kakao" | "google";
    PostId: number;
    CommentId: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  signup: {
    parameters: {
      query?: never;
      header?: {
        /** @description BFF와 API가 공유하는 비밀 키. 맞을 때만 X-Ogu-Client-Ip를 믿는다. */
        "X-Ogu-Bff-Key"?: components["parameters"]["BffKey"];
        /** @description 브라우저의 원래 IP. 로그인 실패 제한에 쓴다. */
        "X-Ogu-Client-Ip"?: components["parameters"]["ClientIp"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailPasswordRequest"];
      };
    };
    responses: {
      /** @description 가입과 동시에 로그인된다. member.onboarded는 false다. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResultEnvelope"];
        };
      };
      400: components["responses"]["BadRequest"];
      /** @description 이미 가입된 이메일(EMAIL_ALREADY_REGISTERED), 또는 외부 계정 회원이 쓰는 이메일(EMAIL_REGISTERED_WITH_OTHER_METHOD) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: {
        /** @description BFF와 API가 공유하는 비밀 키. 맞을 때만 X-Ogu-Client-Ip를 믿는다. */
        "X-Ogu-Bff-Key"?: components["parameters"]["BffKey"];
        /** @description 브라우저의 원래 IP. 로그인 실패 제한에 쓴다. */
        "X-Ogu-Client-Ip"?: components["parameters"]["ClientIp"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailPasswordRequest"];
      };
    };
    responses: {
      /** @description 로그인 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResultEnvelope"];
        };
      };
      400: components["responses"]["BadRequest"];
      /** @description 이메일 또는 비밀번호가 틀림. 어느 쪽인지 구분하지 않는다 (INVALID_CREDENTIALS) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description 로그인 실패 제한에 걸림 (LOGIN_THROTTLED). error.retryAfterSeconds와 Retry-After 헤더가 있다 */
      429: {
        headers: {
          "Retry-After"?: number;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  oauthLogin: {
    parameters: {
      query?: never;
      header?: {
        /** @description BFF와 API가 공유하는 비밀 키. 맞을 때만 X-Ogu-Client-Ip를 믿는다. */
        "X-Ogu-Bff-Key"?: components["parameters"]["BffKey"];
        /** @description 브라우저의 원래 IP. 로그인 실패 제한에 쓴다. */
        "X-Ogu-Client-Ip"?: components["parameters"]["ClientIp"];
      };
      path: {
        provider: components["parameters"]["Provider"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          code: string;
          /**
           * Format: uri
           * @description 인가 요청에 쓴 redirect_uri와 같아야 한다. API는 허용 목록과 대조한다
           */
          redirectUri: string;
          /** @description PKCE를 쓴 경우에만 보낸다 */
          codeVerifier?: string | null;
        };
      };
    };
    responses: {
      /** @description 로그인 성공. 처음이면 newMember=true, member.onboarded=false */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResultEnvelope"];
        };
      };
      400: components["responses"]["BadRequest"];
      /** @description 제공자가 코드를 거절함 (OAUTH_CODE_INVALID) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description 같은 이메일이 이메일 가입으로 이미 쓰임 (EMAIL_REGISTERED_WITH_OTHER_METHOD) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description 제공자가 응답하지 않음 (OAUTH_PROVIDER_UNAVAILABLE) */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: {
        /** @description BFF와 API가 공유하는 비밀 키. 맞을 때만 X-Ogu-Client-Ip를 믿는다. */
        "X-Ogu-Bff-Key"?: components["parameters"]["BffKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          refreshToken: string;
        };
      };
    };
    responses: {
      /** @description 새 토큰. 유예 구간에서는 tokens.refreshToken이 null */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResultEnvelope"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 세션이 무효가 되었다. 이미 무효이거나 만료된 세션의 토큰은 401이다(BFF는 결과와 관계없이 쿠키를 지운다) */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 내 프로필 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberProfileEnvelope"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  checkNickname: {
    parameters: {
      query: {
        nickname: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 사용 가능 여부 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            success: true;
            data: components["schemas"]["NicknameAvailability"];
            error: null;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  completeOnboarding: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          nickname: string;
          jobRole: components["schemas"]["JobRole"];
          careerYear: components["schemas"]["CareerYear"];
        };
      };
    };
    responses: {
      /** @description 온보딩 완료. 새 access 토큰을 함께 준다 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            success: true;
            data: components["schemas"]["OnboardingResult"];
            error: null;
          };
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      /** @description 닉네임 중복(NICKNAME_TAKEN) 또는 이미 온보딩함(ALREADY_ONBOARDED) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  createPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PostWriteRequest"];
      };
    };
    responses: {
      /** @description 저장됨. analysisStatus는 PENDING */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            success: true;
            data: components["schemas"]["PostCreated"];
            error: null;
          };
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      /** @description 1시간에 10개 초과 (POST_RATE_LIMITED, research R9) */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  getPostDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: components["parameters"]["PostId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 글 상세 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            success: true;
            data: components["schemas"]["PostDetail"];
            error: null;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  deletePost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: components["parameters"]["PostId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 삭제됨 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  updatePost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: components["parameters"]["PostId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PostUpdateRequest"];
      };
    };
    responses: {
      /** @description 수정됨 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  getFeed: {
    parameters: {
      query?: {
        order?: "LATEST" | "POPULAR";
        /** @description 여러 번 줄 수 있다. 하나라도 맞으면 통과 */
        jobRole?: components["schemas"]["JobRole"][];
        careerYear?: components["schemas"]["CareerYear"][];
        cursor?: string;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 피드 페이지 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            success: true;
            data: components["schemas"]["FeedPage"];
            error: null;
          };
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
    };
  };
  likePost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: components["parameters"]["PostId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 공감됨 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            success: true;
            data: components["schemas"]["LikeResult"];
            error: null;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      /** @description 이미 공감함 (ALREADY_LIKED) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  unlikePost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: components["parameters"]["PostId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 취소됨. 공감하지 않은 상태여도 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            success: true;
            data: components["schemas"]["LikeResult"];
            error: null;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  getComments: {
    parameters: {
      query?: {
        cursor?: string;
      };
      header?: never;
      path: {
        postId: components["parameters"]["PostId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 댓글 페이지 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            success: true;
            data: components["schemas"]["CommentPage"];
            error: null;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  createComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: components["parameters"]["PostId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CommentWriteRequest"];
      };
    };
    responses: {
      /** @description 작성됨 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            success: true;
            data: components["schemas"]["Comment"];
            error: null;
          };
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  deleteComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        commentId: components["parameters"]["CommentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 삭제됨 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  updateComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        commentId: components["parameters"]["CommentId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          content: string;
        };
      };
    };
    responses: {
      /** @description 수정됨 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  likeComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        commentId: components["parameters"]["CommentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 공감됨 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            success: true;
            data: components["schemas"]["LikeResult"];
            error: null;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      /** @description 이미 공감함 (ALREADY_LIKED) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  unlikeComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        commentId: components["parameters"]["CommentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 취소됨 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            success: true;
            data: components["schemas"]["LikeResult"];
            error: null;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
}
