-- 002-auth: 회원, 외부 계정 연결, 세션, 로그인 실패 기록
-- 스키마는 specs/002-auth/data-model.md 그대로 만든다.

CREATE TABLE member
(
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_method    VARCHAR(10) NOT NULL,
  email          VARCHAR(254),
  password_hash  VARCHAR(100),
  nickname       VARCHAR(10),
  nickname_key   VARCHAR(10) UNIQUE,
  job_role       VARCHAR(20),
  career_year    VARCHAR(20),
  onboarded_at   TIMESTAMPTZ,
  created_at     TIMESTAMPTZ NOT NULL,
  updated_at     TIMESTAMPTZ NOT NULL,
  CONSTRAINT member_auth_method_check
    CHECK (auth_method IN ('EMAIL', 'KAKAO', 'GOOGLE')),
  CONSTRAINT member_email_password_required_for_email_check
    CHECK (auth_method <> 'EMAIL' OR (email IS NOT NULL AND password_hash IS NOT NULL)),
  CONSTRAINT member_onboarding_fields_required_check
    CHECK (
      onboarded_at IS NULL
        OR (nickname IS NOT NULL AND nickname_key IS NOT NULL AND job_role IS NOT NULL AND career_year IS NOT NULL)
    )
);

-- 이메일 가입끼리의 중복만 막는다. 외부 계정끼리는 이메일이 겹쳐도 된다.
CREATE UNIQUE INDEX member_email_key ON member (email) WHERE auth_method = 'EMAIL';

CREATE TABLE oauth_identity
(
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id         BIGINT NOT NULL REFERENCES member (id),
  provider          VARCHAR(10) NOT NULL,
  provider_user_id  VARCHAR(255) NOT NULL,
  email             VARCHAR(254),
  created_at        TIMESTAMPTZ NOT NULL,
  CONSTRAINT oauth_identity_provider_check
    CHECK (provider IN ('KAKAO', 'GOOGLE')),
  CONSTRAINT oauth_identity_provider_user_key
    UNIQUE (provider, provider_user_id),
  CONSTRAINT oauth_identity_member_provider_key
    UNIQUE (member_id, provider)
);

CREATE TABLE auth_session
(
  id                            UUID PRIMARY KEY,
  member_id                     BIGINT NOT NULL REFERENCES member (id),
  refresh_token_hash            CHAR(64) NOT NULL UNIQUE,
  previous_refresh_token_hash   CHAR(64) UNIQUE,
  rotated_at                    TIMESTAMPTZ,
  created_at                    TIMESTAMPTZ NOT NULL,
  expires_at                    TIMESTAMPTZ NOT NULL,
  absolute_expires_at           TIMESTAMPTZ NOT NULL,
  revoked_at                    TIMESTAMPTZ,
  revoke_reason                 VARCHAR(20),
  CONSTRAINT auth_session_revoke_reason_check
    CHECK (revoke_reason IS NULL OR revoke_reason IN ('LOGOUT', 'REUSE_DETECTED'))
);

CREATE INDEX auth_session_member_id_idx ON auth_session (member_id);

CREATE TABLE login_attempt
(
  scope_key          VARCHAR(300) PRIMARY KEY,
  window_started_at  TIMESTAMPTZ NOT NULL,
  failure_count      INT NOT NULL,
  blocked_until      TIMESTAMPTZ
);
