-- 003-core-loop: 고민 글, 댓글, 공감, 감정 분석, 몬스터, HP 기록
-- 스키마는 specs/003-core-loop/data-model.md 그대로 만든다.
-- 제약은 모두 이름을 붙인다. 애플리케이션이 위반을 제약 이름으로 구분한다(예: post_likes_pkey → ALREADY_LIKED).
-- 모듈 경계를 넘는 참조(emotion_analysis.post_id, monsters.post_id, monster_hp_log.member_id)에는 FK를 두지 않는다.

-- post 모듈 ---------------------------------------------------------------

CREATE TABLE posts
(
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
  author_id           BIGINT NOT NULL,
  author_job_role     VARCHAR(20) NOT NULL,
  author_career_year  VARCHAR(20) NOT NULL,
  content             VARCHAR(2000) NOT NULL,
  comment_tone        VARCHAR(20) NOT NULL,
  like_count          INT NOT NULL DEFAULT 0,
  comment_count       INT NOT NULL DEFAULT 0,
  deleted_at          TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL,
  updated_at          TIMESTAMPTZ NOT NULL,
  CONSTRAINT posts_pkey PRIMARY KEY (id),
  CONSTRAINT posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES member (id),
  CONSTRAINT posts_comment_tone_check
    CHECK (comment_tone IN ('VENT_WITH_ME', 'COMFORT_ME', 'WARM_ADVICE', 'MAKE_ME_LAUGH')),
  CONSTRAINT posts_like_count_check CHECK (like_count >= 0),
  CONSTRAINT posts_comment_count_check CHECK (comment_count >= 0)
);

-- 피드 최신순, 공감순, 직군과 경력 필터(research R7), 작성 제한(research R9)
CREATE INDEX posts_feed_latest_idx ON posts (id DESC) WHERE deleted_at IS NULL;
CREATE INDEX posts_feed_popular_idx ON posts (like_count DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX posts_feed_author_profile_idx ON posts (author_job_role, author_career_year) WHERE deleted_at IS NULL;
CREATE INDEX posts_author_created_at_idx ON posts (author_id, created_at);

CREATE TABLE comments
(
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  post_id     BIGINT NOT NULL,
  author_id   BIGINT NOT NULL,
  parent_id   BIGINT,
  content     VARCHAR(1200) NOT NULL,
  like_count  INT NOT NULL DEFAULT 0,
  deleted_at  TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL,
  updated_at  TIMESTAMPTZ NOT NULL,
  CONSTRAINT comments_pkey PRIMARY KEY (id),
  CONSTRAINT comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES posts (id),
  CONSTRAINT comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES member (id),
  CONSTRAINT comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES comments (id),
  CONSTRAINT comments_like_count_check CHECK (like_count >= 0)
);

CREATE INDEX comments_post_parent_id_idx ON comments (post_id, parent_id, id);

CREATE TABLE post_likes
(
  post_id     BIGINT NOT NULL,
  member_id   BIGINT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL,
  CONSTRAINT post_likes_pkey PRIMARY KEY (post_id, member_id),
  CONSTRAINT post_likes_post_id_fkey FOREIGN KEY (post_id) REFERENCES posts (id),
  CONSTRAINT post_likes_member_id_fkey FOREIGN KEY (member_id) REFERENCES member (id)
);

CREATE TABLE comment_likes
(
  comment_id  BIGINT NOT NULL,
  member_id   BIGINT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL,
  CONSTRAINT comment_likes_pkey PRIMARY KEY (comment_id, member_id),
  CONSTRAINT comment_likes_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES comments (id),
  CONSTRAINT comment_likes_member_id_fkey FOREIGN KEY (member_id) REFERENCES member (id)
);

-- emotion 모듈 ------------------------------------------------------------

CREATE TABLE emotion_analysis
(
  post_id          BIGINT NOT NULL,
  status           VARCHAR(10) NOT NULL,
  emotion          VARCHAR(20),
  intensity        VARCHAR(10),
  reason           VARCHAR(200),
  attempts         INT NOT NULL DEFAULT 0,
  next_attempt_at  TIMESTAMPTZ NOT NULL,
  last_error       VARCHAR(200),
  post_created_at  TIMESTAMPTZ NOT NULL,
  completed_at     TIMESTAMPTZ,
  CONSTRAINT emotion_analysis_pkey PRIMARY KEY (post_id),
  CONSTRAINT emotion_analysis_status_check CHECK (status IN ('PENDING', 'ANALYZED', 'DEFAULTED')),
  CONSTRAINT emotion_analysis_emotion_check
    CHECK (emotion IS NULL OR emotion IN ('ANXIETY', 'LETHARGY', 'LONELINESS', 'SELF_DEPRECATION', 'IRRITATION')),
  CONSTRAINT emotion_analysis_intensity_check CHECK (intensity IS NULL OR intensity IN ('LOW', 'MEDIUM', 'HIGH')),
  CONSTRAINT emotion_analysis_result_required_check
    CHECK (status = 'PENDING' OR (emotion IS NOT NULL AND intensity IS NOT NULL))
);

-- 재시도 스케줄러가 기한이 된 PENDING만 훑는다
CREATE INDEX emotion_analysis_pending_idx ON emotion_analysis (next_attempt_at) WHERE status = 'PENDING';

-- monster 모듈 ------------------------------------------------------------

CREATE TABLE monsters
(
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  post_id      BIGINT NOT NULL,
  emotion      VARCHAR(20) NOT NULL,
  max_hp       INT NOT NULL,
  hp           INT NOT NULL,
  status       VARCHAR(10) NOT NULL,
  defeated_at  TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL,
  CONSTRAINT monsters_pkey PRIMARY KEY (id),
  CONSTRAINT monsters_post_id_key UNIQUE (post_id),
  CONSTRAINT monsters_emotion_check
    CHECK (emotion IN ('ANXIETY', 'LETHARGY', 'LONELINESS', 'SELF_DEPRECATION', 'IRRITATION')),
  CONSTRAINT monsters_max_hp_check CHECK (max_hp IN (10, 20, 30)),
  CONSTRAINT monsters_hp_range_check CHECK (hp >= 0 AND hp <= max_hp),
  CONSTRAINT monsters_status_check CHECK (status IN ('ALIVE', 'DEFEATED')),
  CONSTRAINT monsters_defeated_hp_check CHECK ((status = 'DEFEATED') = (hp = 0))
);

CREATE TABLE monster_hp_log
(
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  monster_id   BIGINT NOT NULL,
  member_id    BIGINT NOT NULL,
  action       VARCHAR(15) NOT NULL,
  target_id    BIGINT NOT NULL,
  hp_delta     INT NOT NULL,
  hp_before    INT NOT NULL,
  hp_after     INT NOT NULL,
  retroactive  BOOLEAN NOT NULL DEFAULT false,
  created_at   TIMESTAMPTZ NOT NULL,
  CONSTRAINT monster_hp_log_pkey PRIMARY KEY (id),
  CONSTRAINT monster_hp_log_monster_id_fkey FOREIGN KEY (monster_id) REFERENCES monsters (id),
  -- 공감은 한 번, 댓글 감소는 회원당 글 하나에 한 번, 취소 후 재공감은 다시 줄지 않음(research R5)
  CONSTRAINT monster_hp_log_attack_key UNIQUE (monster_id, member_id, action, target_id),
  CONSTRAINT monster_hp_log_action_check CHECK (action IN ('POST_LIKE', 'COMMENT', 'COMMENT_LIKE')),
  CONSTRAINT monster_hp_log_hp_delta_check CHECK (hp_delta IN (1, 3))
);
