-- 004-notification-mypage: 알림, 회원별 전달 순서, 공감 묶음 참여자, SSE 연결 표, 마이페이지 조회 인덱스
-- 스키마는 specs/004-notification-mypage/data-model.md 그대로 만든다.
-- 제약은 모두 이름을 붙인다. 애플리케이션이 위반을 제약 이름으로 구분한다.
-- 모듈 경계를 넘는 참조(notification의 receiver_id, post_id, comment_id, monster_id, latest_actor_id와
-- like_notification_participant의 post_id, liker_id)에는 FK를 두지 않는다.

-- notification 모듈 -------------------------------------------------------

CREATE TABLE notification
(
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
  receiver_id      BIGINT NOT NULL,
  type             VARCHAR(30) NOT NULL,
  -- 글이 지워져도 알림은 남는다(US2-AC5)
  post_id          BIGINT NOT NULL,
  comment_id       BIGINT,
  monster_id       BIGINT,
  -- 몬스터 알림은 행동한 회원이 없다
  latest_actor_id  BIGINT,
  actor_count      INT NOT NULL DEFAULT 1,
  -- 멱등 키(research R6). 공감 묶음은 NULL이고, NULL끼리는 유일 제약에 걸리지 않는다
  dedup_key        VARCHAR(40),
  -- 회원별 전달 순서 번호. SSE 이벤트 id(research R4)
  seq              BIGINT NOT NULL,
  read_at          TIMESTAMPTZ,
  -- 보관 기간(90일) 기준. 묶음이 갱신돼도 바뀌지 않는다
  created_at       TIMESTAMPTZ NOT NULL,
  updated_at       TIMESTAMPTZ NOT NULL,
  CONSTRAINT notification_pkey PRIMARY KEY (id),
  -- 목록 키셋(seq DESC)과 재전송(seq >)을 같이 맡는다
  CONSTRAINT notification_receiver_seq_key UNIQUE (receiver_id, seq),
  CONSTRAINT notification_receiver_dedup_key UNIQUE (receiver_id, dedup_key),
  CONSTRAINT notification_type_check
    CHECK (type IN ('POST_COMMENT', 'POST_REPLY', 'COMMENT_REPLY', 'POST_LIKE', 'MONSTER_SPAWNED',
                    'MONSTER_DEFEATED', 'MONSTER_DEFEATED_TOGETHER')),
  CONSTRAINT notification_actor_count_check CHECK (actor_count >= 1),
  CONSTRAINT notification_actor_count_like_only_check CHECK (type = 'POST_LIKE' OR actor_count = 1),
  CONSTRAINT notification_like_dedup_key_check CHECK (type <> 'POST_LIKE' OR dedup_key IS NULL)
);

-- 안 읽은 공감 묶음은 글마다 하나(research R7). 조건이 붙어 있어 제약이 아니라 유일 인덱스다.
-- 이 인덱스를 쓰는 ON CONFLICT는 같은 조건식을 되풀이한다:
--   ON CONFLICT (receiver_id, post_id) WHERE type = 'POST_LIKE' AND read_at IS NULL
CREATE UNIQUE INDEX notification_unread_like_group_key
  ON notification (receiver_id, post_id) WHERE type = 'POST_LIKE' AND read_at IS NULL;

-- 안 읽은 수(research R11)
CREATE INDEX notification_unread_idx ON notification (receiver_id) WHERE read_at IS NULL;

-- 90일 정리 작업(research R10)
CREATE INDEX notification_created_at_idx ON notification (created_at);

CREATE TABLE notification_sequence
(
  member_id  BIGINT NOT NULL,
  last_seq   BIGINT NOT NULL,
  CONSTRAINT notification_sequence_pkey PRIMARY KEY (member_id),
  CONSTRAINT notification_sequence_last_seq_check CHECK (last_seq >= 0)
);

-- 쓰기 순서: 묶음 갱신 또는 생성 → 그 ID로 참여자 삽입(research R7)
CREATE TABLE like_notification_participant
(
  post_id          BIGINT NOT NULL,
  liker_id         BIGINT NOT NULL,
  notification_id  BIGINT NOT NULL,
  created_at       TIMESTAMPTZ NOT NULL,
  -- 같은 회원의 같은 글 공감은 한 번만 알린다
  CONSTRAINT like_notification_participant_pkey PRIMARY KEY (post_id, liker_id),
  CONSTRAINT like_notification_participant_notification_id_fkey
    FOREIGN KEY (notification_id) REFERENCES notification (id) ON DELETE CASCADE
);

CREATE INDEX like_notification_participant_notification_id_idx ON like_notification_participant (notification_id);

-- member 모듈 -------------------------------------------------------------

-- SSE 연결 표(research R3). 원문은 저장하지 않고 SHA-256 16진수만 둔다
CREATE TABLE sse_ticket
(
  token_hash  CHAR(64) NOT NULL,
  member_id   BIGINT NOT NULL,
  session_id  UUID NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  used_at     TIMESTAMPTZ,
  CONSTRAINT sse_ticket_pkey PRIMARY KEY (token_hash),
  CONSTRAINT sse_ticket_member_id_fkey FOREIGN KEY (member_id) REFERENCES member (id),
  CONSTRAINT sse_ticket_expiry_check CHECK (expires_at > created_at)
);

-- 하루 지난 표 정리
CREATE INDEX sse_ticket_expires_at_idx ON sse_ticket (expires_at);

-- post 모듈: 마이페이지 키셋(research R12) ------------------------------------

CREATE INDEX posts_author_live_idx ON posts (author_id, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX comments_author_live_idx ON comments (author_id, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX post_likes_member_created_idx ON post_likes (member_id, created_at DESC, post_id DESC);

-- monster 모듈: 함께 물리친 몬스터(research R12) ------------------------------

CREATE INDEX monster_hp_log_member_monster_idx ON monster_hp_log (member_id, monster_id);
