-- 005-safety: 숨김 상태와 위험 단계, 운영자 역할, 위험 판정, 신고, 재검토 요청, 처리 기록, 낱말 목록, 도움 리소스
-- 스키마는 specs/005-safety/data-model.md 그대로 만든다.
-- 제약은 모두 이름을 붙인다. 애플리케이션이 위반을 제약 이름으로 구분한다.
-- 모듈 경계를 넘는 참조(safety 테이블의 target_id, post_id, author_id, reporter_id, requester_id, operator_id)에는 FK를 두지 않는다.

-- post 모듈: 숨김과 단계 (research R5, R7, R11) -------------------------------

ALTER TABLE posts
  ADD COLUMN hidden_at            TIMESTAMPTZ,
  ADD COLUMN hidden_reason        VARCHAR(20),
  ADD COLUMN risk_level           VARCHAR(10) NOT NULL DEFAULT 'NONE',
  ADD COLUMN review_requested_at  TIMESTAMPTZ,
  -- 숨긴 시각과 이유는 함께 있거나 함께 없다
  ADD CONSTRAINT posts_hidden_pair_check CHECK ((hidden_at IS NULL) = (hidden_reason IS NULL)),
  ADD CONSTRAINT posts_hidden_reason_check CHECK (hidden_reason IS NULL OR hidden_reason IN ('RISK', 'OPERATOR')),
  ADD CONSTRAINT posts_risk_level_check CHECK (risk_level IN ('NONE', 'CONCERN', 'CRISIS'));

ALTER TABLE comments
  ADD COLUMN hidden_at            TIMESTAMPTZ,
  ADD COLUMN hidden_reason        VARCHAR(20),
  ADD COLUMN risk_level           VARCHAR(10) NOT NULL DEFAULT 'NONE',
  ADD COLUMN review_requested_at  TIMESTAMPTZ,
  ADD CONSTRAINT comments_hidden_pair_check CHECK ((hidden_at IS NULL) = (hidden_reason IS NULL)),
  ADD CONSTRAINT comments_hidden_reason_check CHECK (hidden_reason IS NULL OR hidden_reason IN ('RISK', 'OPERATOR')),
  ADD CONSTRAINT comments_risk_level_check CHECK (risk_level IN ('NONE', 'CONCERN', 'CRISIS'));

-- 다른 회원에게 보이는 글은 지우지 않았고 숨기지 않은 글이다. 피드 인덱스의 조건을 그에 맞춘다.
-- 내 글과 내 댓글 인덱스(posts_author_live_idx, comments_author_live_idx)는 그대로 둔다(작성자는 숨긴 것도 본다).
DROP INDEX posts_feed_latest_idx;
DROP INDEX posts_feed_popular_idx;
DROP INDEX posts_feed_author_profile_idx;
CREATE INDEX posts_feed_latest_idx ON posts (id DESC) WHERE deleted_at IS NULL AND hidden_at IS NULL;
CREATE INDEX posts_feed_popular_idx ON posts (like_count DESC, id DESC)
  WHERE deleted_at IS NULL AND hidden_at IS NULL;
CREATE INDEX posts_feed_author_profile_idx ON posts (author_job_role, author_career_year)
  WHERE deleted_at IS NULL AND hidden_at IS NULL;

-- member 모듈: 운영자 역할 (research R10) ------------------------------------

ALTER TABLE member
  ADD COLUMN role VARCHAR(10) NOT NULL DEFAULT 'MEMBER',
  ADD CONSTRAINT member_role_check CHECK (role IN ('MEMBER', 'OPERATOR'));

-- notification 모듈: 새 종류 셋 (research R8) --------------------------------

ALTER TABLE notification DROP CONSTRAINT notification_type_check;
ALTER TABLE notification
  ADD CONSTRAINT notification_type_check
    CHECK (type IN ('POST_COMMENT', 'POST_REPLY', 'COMMENT_REPLY', 'POST_LIKE', 'MONSTER_SPAWNED',
                    'MONSTER_DEFEATED', 'MONSTER_DEFEATED_TOGETHER',
                    'SUPPORT_NOTICE', 'CONTENT_RESTORED', 'REVIEW_KEPT'));
-- RESTORED:COMMENT:{id}:{actionId}가 40자를 넘을 수 있다
ALTER TABLE notification ALTER COLUMN dedup_key TYPE VARCHAR(60);

-- safety 모듈 -------------------------------------------------------------

-- 대상의 위험 판정 한 번. 대상이 고쳐지면 새 행이 생기고 가장 최근 행이 지금 상태다(research R3, R12).
-- 걸린 표현과 본문 사본은 저장하지 않는다(research R13).
CREATE TABLE risk_assessment
(
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
  target_type      VARCHAR(10) NOT NULL,
  target_id        BIGINT NOT NULL,
  post_id          BIGINT NOT NULL,
  author_id        BIGINT NOT NULL,
  -- 판정한 내용의 updated_at. 고친 뒤 늦게 온 분류 결과를 버리는 기준
  content_version  TIMESTAMPTZ NOT NULL,
  keyword_level    VARCHAR(10) NOT NULL,
  ai_level         VARCHAR(10),
  level            VARCHAR(10) NOT NULL,
  status           VARCHAR(10) NOT NULL,
  attempts         INT NOT NULL DEFAULT 0,
  next_attempt_at  TIMESTAMPTZ NOT NULL,
  last_error       VARCHAR(100),
  reviewed_at      TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL,
  completed_at     TIMESTAMPTZ,
  CONSTRAINT risk_assessment_pkey PRIMARY KEY (id),
  CONSTRAINT risk_assessment_target_type_check CHECK (target_type IN ('POST', 'COMMENT')),
  CONSTRAINT risk_assessment_keyword_level_check CHECK (keyword_level IN ('NONE', 'CONCERN', 'CRISIS')),
  CONSTRAINT risk_assessment_ai_level_check CHECK (ai_level IS NULL OR ai_level IN ('NONE', 'CONCERN', 'CRISIS')),
  CONSTRAINT risk_assessment_level_check CHECK (level IN ('NONE', 'CONCERN', 'CRISIS')),
  CONSTRAINT risk_assessment_status_check CHECK (status IN ('PENDING', 'DONE', 'FALLBACK', 'SUPERSEDED')),
  CONSTRAINT risk_assessment_attempts_check CHECK (attempts >= 0)
);

CREATE INDEX risk_assessment_target_idx ON risk_assessment (target_type, target_id, id DESC);
-- 재시도 스케줄러가 차례가 된 PENDING만 훑는다
CREATE INDEX risk_assessment_pending_idx ON risk_assessment (next_attempt_at) WHERE status = 'PENDING';
-- 운영자 조회
CREATE INDEX risk_assessment_level_idx ON risk_assessment (level, id DESC) WHERE level <> 'NONE';
-- 1년 정리
CREATE INDEX risk_assessment_created_at_idx ON risk_assessment (created_at);

CREATE TABLE report
(
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  reporter_id  BIGINT NOT NULL,
  target_type  VARCHAR(10) NOT NULL,
  target_id    BIGINT NOT NULL,
  post_id      BIGINT NOT NULL,
  reason       VARCHAR(10) NOT NULL,
  -- 200글자(grapheme)까지. 결합 이모지를 생각해 넉넉히 둔다
  detail       VARCHAR(800),
  status       VARCHAR(10) NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL,
  closed_at    TIMESTAMPTZ,
  CONSTRAINT report_pkey PRIMARY KEY (id),
  -- 같은 회원은 같은 대상을 한 번만 신고한다(ALREADY_REPORTED)
  CONSTRAINT report_reporter_target_key UNIQUE (reporter_id, target_type, target_id),
  CONSTRAINT report_target_type_check CHECK (target_type IN ('POST', 'COMMENT')),
  CONSTRAINT report_reason_check CHECK (reason IN ('DANGEROUS', 'ABUSIVE', 'SPAM', 'OTHER')),
  CONSTRAINT report_status_check CHECK (status IN ('PENDING', 'RESOLVED', 'REJECTED', 'CLOSED'))
);

CREATE INDEX report_status_idx ON report (status, id DESC);
-- 대상별 열린 신고 수와 한꺼번에 닫기
CREATE INDEX report_open_target_idx ON report (target_type, target_id) WHERE status = 'PENDING';
-- 한 시간 20건 제한
CREATE INDEX report_reporter_created_at_idx ON report (reporter_id, created_at);
CREATE INDEX report_created_at_idx ON report (created_at);

CREATE TABLE review_request
(
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
  target_type   VARCHAR(10) NOT NULL,
  target_id     BIGINT NOT NULL,
  post_id       BIGINT NOT NULL,
  requester_id  BIGINT NOT NULL,
  status        VARCHAR(10) NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL,
  closed_at     TIMESTAMPTZ,
  CONSTRAINT review_request_pkey PRIMARY KEY (id),
  -- 대상마다 한 번만 요청한다(REVIEW_ALREADY_REQUESTED)
  CONSTRAINT review_request_target_key UNIQUE (target_type, target_id),
  CONSTRAINT review_request_target_type_check CHECK (target_type IN ('POST', 'COMMENT')),
  CONSTRAINT review_request_status_check CHECK (status IN ('PENDING', 'KEPT', 'RESTORED'))
);

CREATE INDEX review_request_status_idx ON review_request (status, id DESC);
CREATE INDEX review_request_created_at_idx ON review_request (created_at);

-- 운영자가 한 일의 기록. 고치거나 지우지 않는다(1년 정리만).
CREATE TABLE moderation_action
(
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  operator_id  BIGINT NOT NULL,
  action       VARCHAR(20) NOT NULL,
  target_type  VARCHAR(10),
  target_id    BIGINT,
  note         VARCHAR(200),
  created_at   TIMESTAMPTZ NOT NULL,
  CONSTRAINT moderation_action_pkey PRIMARY KEY (id),
  CONSTRAINT moderation_action_action_check
    CHECK (action IN ('HIDE', 'UNHIDE', 'RESOLVE_REPORT', 'REJECT_REPORT', 'KEEP_HIDDEN', 'ADD_TERM', 'REMOVE_TERM')),
  CONSTRAINT moderation_action_target_type_check
    CHECK (target_type IS NULL OR target_type IN ('POST', 'COMMENT', 'TERM'))
);

CREATE INDEX moderation_action_created_at_idx ON moderation_action (created_at);
CREATE INDEX moderation_action_target_idx ON moderation_action (target_type, target_id);

-- 키워드 규칙과 욕설 가리기에 쓰는 낱말. term은 정규화한 형태다(research R4).
CREATE TABLE safety_term
(
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  kind        VARCHAR(10) NOT NULL,
  term        VARCHAR(40) NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL,
  updated_at  TIMESTAMPTZ NOT NULL,
  CONSTRAINT safety_term_pkey PRIMARY KEY (id),
  CONSTRAINT safety_term_kind_term_key UNIQUE (kind, term),
  CONSTRAINT safety_term_kind_check CHECK (kind IN ('CRISIS', 'CONCERN', 'PROFANITY', 'ALLOW'))
);

CREATE TABLE support_resource
(
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name           VARCHAR(40) NOT NULL,
  phone          VARCHAR(20) NOT NULL,
  hours          VARCHAR(40) NOT NULL,
  description    VARCHAR(100) NOT NULL,
  display_order  INT NOT NULL,
  active         BOOLEAN NOT NULL DEFAULT true,
  CONSTRAINT support_resource_pkey PRIMARY KEY (id)
);

-- 이미 있는 글과 댓글을 한 번 훑는 작업의 진행 표지(research R14)
CREATE TABLE safety_backfill
(
  target_type  VARCHAR(10) NOT NULL,
  last_id      BIGINT NOT NULL DEFAULT 0,
  finished_at  TIMESTAMPTZ,
  CONSTRAINT safety_backfill_pkey PRIMARY KEY (target_type),
  CONSTRAINT safety_backfill_target_type_check CHECK (target_type IN ('POST', 'COMMENT'))
);

INSERT INTO safety_backfill (target_type) VALUES ('POST'), ('COMMENT');

-- 시드 -------------------------------------------------------------------

-- 번호와 운영 시간은 출시 전에 공식 안내로 다시 확인한다(quickstart 운영 준비 1)
INSERT INTO support_resource (name, phone, hours, description, display_order)
VALUES ('자살예방상담전화', '109', '24시간', '지금 힘든 마음을 이야기할 수 있어요', 1),
       ('정신건강위기상담전화', '1577-0199', '24시간', '가까운 정신건강복지센터로 연결돼요', 2),
       ('청소년상담전화', '1388', '24시간', '청소년과 보호자가 상담받을 수 있어요', 3);

-- 낱말은 정규화한 형태(공백과 기호 없음, 소문자)로 넣는다. 앞의 여섯은 원본(WEBBB)의 위기 표현이다.
INSERT INTO safety_term (kind, term, created_at, updated_at)
SELECT kind, term, now(), now()
FROM (VALUES ('CRISIS', '죽고싶'),
             ('CRISIS', '자살'),
             ('CRISIS', '자해'),
             ('CRISIS', '스스로목숨'),
             ('CRISIS', '삶을끝'),
             ('CRISIS', '죽어버리고싶'),
             ('CRISIS', '목숨을끊'),
             ('CRISIS', '극단적선택'),
             ('CRISIS', '극단적인선택'),
             ('CRISIS', '살고싶지않'),
             ('CRISIS', '생을마감'),
             ('CRISIS', '죽는게낫'),
             ('CONCERN', '살기싫'),
             ('CONCERN', '사라지고싶'),
             ('CONCERN', '다포기하고싶'),
             ('CONCERN', '버틸수없'),
             ('CONCERN', '아무의미없'),
             ('CONCERN', '아무의미가없'),
             ('CONCERN', '왜사는지모르'),
             ('CONCERN', '내일이안왔으면'),
             ('PROFANITY', '씨발'),
             ('PROFANITY', '시발'),
             ('PROFANITY', '병신'),
             ('PROFANITY', '개새끼'),
             ('PROFANITY', '지랄'),
             ('PROFANITY', '좆'),
             ('ALLOW', '시발점'),
             ('ALLOW', '시발역')) AS seed(kind, term);
