-- 006-raid: 보스 레이드 (specs/006-raid/data-model.md)

-- raid 모듈 ----------------------------------------------------------------

CREATE TABLE raid_boss
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
  emotion            VARCHAR(20) NOT NULL,
  max_hp             INT NOT NULL,
  -- 마지막으로 옮겨 적은 남은 HP. 살아 있는 동안의 정확한 값은 Redis에 있다(research R2, R3)
  hp                 INT NOT NULL,
  participant_count  INT NOT NULL DEFAULT 0,
  status             VARCHAR(10) NOT NULL,
  spawned_at         TIMESTAMPTZ NOT NULL,
  ended_at           TIMESTAMPTZ,
  CONSTRAINT raid_boss_pkey PRIMARY KEY (id),
  CONSTRAINT raid_boss_emotion_check
    CHECK (emotion IN ('ANXIETY', 'LETHARGY', 'LONELINESS', 'SELF_DEPRECATION', 'IRRITATION')),
  CONSTRAINT raid_boss_max_hp_check CHECK (max_hp > 0),
  CONSTRAINT raid_boss_hp_check CHECK (hp BETWEEN 0 AND max_hp),
  CONSTRAINT raid_boss_participant_count_check CHECK (participant_count >= 0),
  CONSTRAINT raid_boss_status_check CHECK (status IN ('ALIVE', 'DEFEATED', 'RETREATED')),
  CONSTRAINT raid_boss_ended_pair_check CHECK ((status = 'ALIVE') = (ended_at IS NULL)),
  CONSTRAINT raid_boss_defeated_hp_check CHECK (status <> 'DEFEATED' OR hp = 0)
);

-- 살아 있는 보스는 한 번에 하나다(US5-AC6). 스케줄러의 잠금에 기대지 않는다
CREATE UNIQUE INDEX raid_boss_alive_key ON raid_boss ((true)) WHERE status = 'ALIVE';
CREATE INDEX raid_boss_ended_at_idx ON raid_boss (ended_at DESC);

CREATE TABLE raid_contribution
(
  boss_id          BIGINT NOT NULL,
  member_id        BIGINT NOT NULL,
  -- 받아들여진 공격 수. 늘어나기만 한다
  damage           INT NOT NULL,
  first_attack_at  TIMESTAMPTZ NOT NULL,
  updated_at       TIMESTAMPTZ NOT NULL,
  CONSTRAINT raid_contribution_pkey PRIMARY KEY (boss_id, member_id),
  CONSTRAINT raid_contribution_boss_id_fkey FOREIGN KEY (boss_id) REFERENCES raid_boss (id),
  CONSTRAINT raid_contribution_damage_check CHECK (damage > 0)
);

-- 함께 물리친 보스 수(research R12)
CREATE INDEX raid_contribution_member_idx ON raid_contribution (member_id, boss_id);

-- notification 모듈: 보스 처치 알림 (research R11) ---------------------------

ALTER TABLE notification ALTER COLUMN post_id DROP NOT NULL;
ALTER TABLE notification ADD COLUMN raid_boss_id BIGINT;

ALTER TABLE notification DROP CONSTRAINT notification_type_check;
ALTER TABLE notification
  ADD CONSTRAINT notification_type_check
    CHECK (type IN ('POST_COMMENT', 'POST_REPLY', 'COMMENT_REPLY', 'POST_LIKE', 'MONSTER_SPAWNED',
                    'MONSTER_DEFEATED', 'MONSTER_DEFEATED_TOGETHER', 'SUPPORT_NOTICE', 'CONTENT_RESTORED',
                    'REVIEW_KEPT', 'RAID_BOSS_DEFEATED'));

-- 보스 처치 알림만 글이 없고, 그 알림만 보스를 가리킨다
ALTER TABLE notification
  ADD CONSTRAINT notification_target_check
    CHECK ((type = 'RAID_BOSS_DEFEATED') = (post_id IS NULL)
      AND (type = 'RAID_BOSS_DEFEATED') = (raid_boss_id IS NOT NULL));
