-- 008-weekly-report: 주간 리포트 (specs/008-weekly-report/data-model.md)

-- report 모듈 ----------------------------------------------------------------

-- 회원 한 명의 한 주. 발행할 때의 수치를 그대로 간직한다. 본문, 닉네임, 글 번호를 담지 않는다.
CREATE TABLE weekly_report
(
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
  member_id               BIGINT NOT NULL,
  -- 그 주의 월요일(한국 시간)
  week_start              DATE NOT NULL,
  post_count              INT NOT NULL,
  -- 감정별 글 수. 모든 감정이 키로 있다. 이 값으로 찾거나 거르지 않는다
  emotion_counts          JSONB NOT NULL,
  unanalyzed_count        INT NOT NULL,
  top_emotion             VARCHAR(20),
  defeated_count          INT NOT NULL,
  received_likes          INT NOT NULL,
  received_comments       INT NOT NULL,
  letter_status           VARCHAR(10) NOT NULL,
  letter                  TEXT,
  letter_attempts         INT NOT NULL DEFAULT 0,
  letter_next_attempt_at  TIMESTAMPTZ,
  -- 실패의 분류만 남긴다. 공급자의 답을 담지 않는다
  letter_last_error       VARCHAR(100),
  -- 편지의 24시간 기한과 1년 보관의 기준
  published_at            TIMESTAMPTZ NOT NULL,
  CONSTRAINT weekly_report_pkey PRIMARY KEY (id),
  -- 회원마다, 주마다 하나다. 리포트 만들기가 여러 번, 여러 서버에서 돌아도 겹치지 않게 하는 것이 이 제약이다(research R4)
  CONSTRAINT weekly_report_member_week_key UNIQUE (member_id, week_start),
  CONSTRAINT weekly_report_letter_status_check CHECK (letter_status IN ('PENDING', 'DONE', 'GIVEN_UP', 'SUPPORT')),
  CONSTRAINT weekly_report_letter_check CHECK ((letter_status = 'DONE') = (letter IS NOT NULL)),
  CONSTRAINT weekly_report_letter_pending_check CHECK ((letter_status = 'PENDING') = (letter_next_attempt_at IS NOT NULL)),
  CONSTRAINT weekly_report_counts_check
    CHECK (post_count >= 1 AND unanalyzed_count >= 0 AND defeated_count >= 0
      AND received_likes >= 0 AND received_comments >= 0 AND letter_attempts >= 0),
  CONSTRAINT weekly_report_top_emotion_check
    CHECK (top_emotion IS NULL
      OR top_emotion IN ('ANXIETY', 'LETHARGY', 'LONELINESS', 'SELF_DEPRECATION', 'IRRITATION')),
  CONSTRAINT weekly_report_week_start_check CHECK (EXTRACT(ISODOW FROM week_start) = 1)
);

-- 편지 재시도가 나중에 발행된 것부터 잡는다(007에서 배운 것: 밀린 것이 새것을 막지 않게)
CREATE INDEX weekly_report_letter_pending_idx ON weekly_report (published_at DESC) WHERE letter_status = 'PENDING';
-- 1년 지난 것을 지울 때
CREATE INDEX weekly_report_published_idx ON weekly_report (published_at);

-- 어느 주의 리포트 만들기가 끝났는지. 행이 있으면 그 주는 다시 훑지 않는다.
CREATE TABLE weekly_report_run
(
  week_start    DATE NOT NULL,
  completed_at  TIMESTAMPTZ NOT NULL,
  CONSTRAINT weekly_report_run_pkey PRIMARY KEY (week_start)
);

-- notification 모듈: 주간 리포트 알림 --------------------------------------------

ALTER TABLE notification ADD COLUMN report_week_start DATE;

ALTER TABLE notification DROP CONSTRAINT notification_type_check;
ALTER TABLE notification
  ADD CONSTRAINT notification_type_check
    CHECK (type IN ('POST_COMMENT', 'POST_REPLY', 'COMMENT_REPLY', 'POST_LIKE', 'MONSTER_SPAWNED',
                    'MONSTER_DEFEATED', 'MONSTER_DEFEATED_TOGETHER', 'SUPPORT_NOTICE', 'CONTENT_RESTORED',
                    'REVIEW_KEPT', 'RAID_BOSS_DEFEATED', 'WEEKLY_REPORT'));

-- 보스 처치와 주간 리포트 알림만 글이 없다. 보스 알림만 보스를, 리포트 알림만 주를 가리킨다
ALTER TABLE notification DROP CONSTRAINT notification_target_check;
ALTER TABLE notification
  ADD CONSTRAINT notification_target_check
    CHECK ((type IN ('RAID_BOSS_DEFEATED', 'WEEKLY_REPORT')) = (post_id IS NULL)
      AND (type = 'RAID_BOSS_DEFEATED') = (raid_boss_id IS NOT NULL)
      AND (type = 'WEEKLY_REPORT') = (report_week_start IS NOT NULL));

-- post 모듈: 리포트가 기간으로 읽는다(research R5) ---------------------------------

-- 그 주에 글을 쓴 회원 찾기
CREATE INDEX posts_created_author_idx ON posts (created_at, author_id) WHERE deleted_at IS NULL;
-- 내 글에 그 주에 달린 공감 세기
CREATE INDEX post_likes_post_created_idx ON post_likes (post_id, created_at);
